### ISSUE TITLE
Image loading; lazy loading?

### ISSUE THREAD

**Issue by krijnhoetmer** [RalphKocken/i-love-web-app#2]
Kijk eens of je sommige afbeeldingen via loading="lazy" later in kunt laden, want nu wordt alles in 1 klap geladen.

https://github.com/RalphKocken/i-love-web-app/blob/ef1280190f0d640c6f9ca1a2390bc4ede7ce54a7/src/lib/components/molecules/Article.svelte#L6

**Comment by RalphKocken** [comment]
gefixt!

**Comment by KrijnHoetmer** [comment]
Mjah, niet helemaal, want dat staat nu op _alle_ afbeeldingen, ook je LCP/eerste image. Probeer dit alleen op afbeeldingen te zetten die niet z.s.m. ingeladen hoeven te worden.
